# Numpy

In [1]:
import numpy as np

In [2]:
# matriz
a=np.random.random((10,4))
a

array([[0.01733484, 0.87489855, 0.66409092, 0.08008466],
       [0.38574169, 0.85367326, 0.55649259, 0.11081625],
       [0.18910638, 0.21608436, 0.47976771, 0.54687445],
       [0.13002704, 0.97636184, 0.33887282, 0.22873085],
       [0.75652062, 0.27855374, 0.068987  , 0.31648942],
       [0.47703189, 0.41319131, 0.94953295, 0.28593424],
       [0.82566561, 0.07674766, 0.54446454, 0.19239926],
       [0.35370038, 0.47614875, 0.15385181, 0.79406025],
       [0.16727522, 0.50411282, 0.64836588, 0.1742123 ],
       [0.31731437, 0.39769779, 0.0334028 , 0.52873753]])

In [3]:
a.size

40

In [4]:
a.shape

(10, 4)

In [5]:
# cubo
b=np.random.random((5,3,2))
b

array([[[0.8180361 , 0.45600498],
        [0.04471126, 0.34612086],
        [0.30714511, 0.44638296]],

       [[0.21723355, 0.14495298],
        [0.1534135 , 0.57836215],
        [0.68645639, 0.08419984]],

       [[0.95556353, 0.72185678],
        [0.35789369, 0.59625938],
        [0.6629485 , 0.25928965]],

       [[0.946139  , 0.16530205],
        [0.54314783, 0.46087273],
        [0.79653774, 0.15828406]],

       [[0.09042659, 0.42157672],
        [0.29883988, 0.25327702],
        [0.65605426, 0.26425126]]])

In [7]:
# tensor rango 4
c=np.random.random((2,3,4,5))
c.shape

(2, 3, 4, 5)

In [9]:
type(a[0])

numpy.ndarray

In [11]:
a

array([[0.01733484, 0.87489855, 0.66409092, 0.08008466],
       [0.38574169, 0.85367326, 0.55649259, 0.11081625],
       [0.18910638, 0.21608436, 0.47976771, 0.54687445],
       [0.13002704, 0.97636184, 0.33887282, 0.22873085],
       [0.75652062, 0.27855374, 0.068987  , 0.31648942],
       [0.47703189, 0.41319131, 0.94953295, 0.28593424],
       [0.82566561, 0.07674766, 0.54446454, 0.19239926],
       [0.35370038, 0.47614875, 0.15385181, 0.79406025],
       [0.16727522, 0.50411282, 0.64836588, 0.1742123 ],
       [0.31731437, 0.39769779, 0.0334028 , 0.52873753]])

In [10]:
a[:, 0]

array([0.01733484, 0.38574169, 0.18910638, 0.13002704, 0.75652062,
       0.47703189, 0.82566561, 0.35370038, 0.16727522, 0.31731437])

In [12]:
a[4,2]

0.06898700300815497

In [13]:
c[0]

array([[[0.89390951, 0.31186455, 0.47982635, 0.98359641, 0.79125905],
        [0.91623549, 0.39573239, 0.81433373, 0.91374181, 0.81585122],
        [0.75451558, 0.58885519, 0.64667176, 0.65330878, 0.69278229],
        [0.09356   , 0.41268999, 0.12248687, 0.6972889 , 0.87776445]],

       [[0.9564918 , 0.31607421, 0.96360239, 0.61695367, 0.32771823],
        [0.32110885, 0.59432915, 0.1093376 , 0.92344875, 0.50796882],
        [0.9426791 , 0.89869711, 0.39673523, 0.27731114, 0.57287862],
        [0.58081385, 0.33051236, 0.52592781, 0.00888726, 0.77023635]],

       [[0.43365704, 0.0688031 , 0.2894688 , 0.64358397, 0.45596058],
        [0.183023  , 0.82854817, 0.67222816, 0.78330057, 0.73464812],
        [0.39258773, 0.71910277, 0.59520887, 0.27487641, 0.50985739],
        [0.48353033, 0.67787299, 0.59794252, 0.03005514, 0.45791013]]])

In [14]:
c[0, 1]

array([[0.9564918 , 0.31607421, 0.96360239, 0.61695367, 0.32771823],
       [0.32110885, 0.59432915, 0.1093376 , 0.92344875, 0.50796882],
       [0.9426791 , 0.89869711, 0.39673523, 0.27731114, 0.57287862],
       [0.58081385, 0.33051236, 0.52592781, 0.00888726, 0.77023635]])

In [15]:
c[0, 1, 1]

array([0.32110885, 0.59432915, 0.1093376 , 0.92344875, 0.50796882])

In [16]:
c[0, 1, 1, 0]

0.32110885294305835

In [17]:
c[0, 1, :, 0]

array([0.9564918 , 0.32110885, 0.9426791 , 0.58081385])

In [23]:
# de listas a arrays
lst_lst=[[1,2,3], [4,5,6], [7,8,9]]
d=np.array(lst_lst)
d.shape

(3, 3)

In [25]:
a

array([[0.01733484, 0.87489855, 0.66409092, 0.08008466],
       [0.38574169, 0.85367326, 0.55649259, 0.11081625],
       [0.18910638, 0.21608436, 0.47976771, 0.54687445],
       [0.13002704, 0.97636184, 0.33887282, 0.22873085],
       [0.75652062, 0.27855374, 0.068987  , 0.31648942],
       [0.47703189, 0.41319131, 0.94953295, 0.28593424],
       [0.82566561, 0.07674766, 0.54446454, 0.19239926],
       [0.35370038, 0.47614875, 0.15385181, 0.79406025],
       [0.16727522, 0.50411282, 0.64836588, 0.1742123 ],
       [0.31731437, 0.39769779, 0.0334028 , 0.52873753]])

In [24]:
# funciones matematicas
np.sum(a)

16.383356352932523

In [31]:
s=np.sum(a, axis=0)
np.sum(s, axis=0)

16.383356352932523

In [26]:
np.sum(a, axis=0)

array([3.61971805, 5.06747007, 4.43782903, 3.2583392 ])

In [27]:
np.sum(a, axis=1)

array([1.63640898, 1.9067238 , 1.43183291, 1.67399255, 1.42055077,
       2.12569039, 1.63927706, 1.77776119, 1.49396622, 1.27715249])

In [28]:
np.sum(a, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [32]:
b

array([[[0.8180361 , 0.45600498],
        [0.04471126, 0.34612086],
        [0.30714511, 0.44638296]],

       [[0.21723355, 0.14495298],
        [0.1534135 , 0.57836215],
        [0.68645639, 0.08419984]],

       [[0.95556353, 0.72185678],
        [0.35789369, 0.59625938],
        [0.6629485 , 0.25928965]],

       [[0.946139  , 0.16530205],
        [0.54314783, 0.46087273],
        [0.79653774, 0.15828406]],

       [[0.09042659, 0.42157672],
        [0.29883988, 0.25327702],
        [0.65605426, 0.26425126]]])

In [33]:
np.sum(b[:2])

4.283019681095566

In [34]:
np.mean(a)

0.4095839088233131

In [35]:
np.mean(a, axis=0)

array([0.3619718 , 0.50674701, 0.4437829 , 0.32583392])

In [36]:
np.mean(a, axis=1)

array([0.40910224, 0.47668095, 0.35795823, 0.41849814, 0.35513769,
       0.5314226 , 0.40981927, 0.4444403 , 0.37349155, 0.31928812])

In [37]:
np.add(a[0], a[1])

array([0.40307653, 1.72857181, 1.22058352, 0.19090091])

In [38]:
np.add(b[0], b[1])

array([[1.03526965, 0.60095796],
       [0.19812476, 0.92448301],
       [0.9936015 , 0.5305828 ]])

In [39]:
np.subtract(a[0], a[1])

array([-0.36840685,  0.02122529,  0.10759833, -0.03073158])

In [40]:
np.multiply(a[0], a[1])

array([0.00668677, 0.7468775 , 0.36956168, 0.00887468])

In [42]:
np.std(a, axis=0)

array([0.2503816 , 0.28626482, 0.27825493, 0.21628505])

In [43]:
np.std(a, axis=1)

array([0.36868676, 0.26954593, 0.15745319, 0.3304464 , 0.25017457,
       0.25100687, 0.29549352, 0.23233324, 0.20907846, 0.18148791])

In [44]:
np.cumsum(a)

array([ 0.01733484,  0.89223339,  1.55632431,  1.63640898,  2.02215067,
        2.87582393,  3.43231652,  3.54313277,  3.73223916,  3.94832352,
        4.42809123,  4.97496568,  5.10499272,  6.08135456,  6.42022738,
        6.64895823,  7.40547884,  7.68403258,  7.75301959,  8.069509  ,
        8.54654089,  8.9597322 ,  9.90926515, 10.19519939, 11.020865  ,
       11.09761266, 11.6420772 , 11.83447646, 12.18817684, 12.66432559,
       12.81817739, 13.61223764, 13.77951287, 14.28362568, 14.93199156,
       15.10620386, 15.42351823, 15.82121602, 15.85461882, 16.38335635])

In [46]:
np.cumprod(a)

array([1.73348381e-02, 1.51662248e-02, 1.00717522e-02, 8.06592893e-04,
       3.11136508e-04, 2.65608917e-04, 1.47809395e-04, 1.63796828e-05,
       3.09750260e-06, 6.69321874e-07, 3.21119026e-07, 1.75611789e-07,
       2.28342813e-08, 2.22945208e-08, 7.55500711e-09, 1.72806320e-09,
       1.30731544e-09, 3.64157604e-10, 2.51221417e-11, 7.95089197e-12,
       3.79282904e-12, 1.56716398e-12, 1.48807384e-12, 4.25491265e-13,
       3.51313505e-13, 2.69624885e-14, 1.46801189e-14, 2.82444396e-15,
       9.99006911e-16, 4.75675891e-16, 7.31835950e-17, 5.81121838e-17,
       9.72072841e-18, 4.90034380e-18, 3.17721572e-18, 5.53510043e-19,
       1.75636690e-19, 6.98503238e-20, 2.33319669e-21, 1.23364865e-21])

In [49]:
b.flatten()

array([0.8180361 , 0.45600498, 0.04471126, 0.34612086, 0.30714511,
       0.44638296, 0.21723355, 0.14495298, 0.1534135 , 0.57836215,
       0.68645639, 0.08419984, 0.95556353, 0.72185678, 0.35789369,
       0.59625938, 0.6629485 , 0.25928965, 0.946139  , 0.16530205,
       0.54314783, 0.46087273, 0.79653774, 0.15828406, 0.09042659,
       0.42157672, 0.29883988, 0.25327702, 0.65605426, 0.26425126])

In [53]:
b.max()

0.955563528278025

In [54]:
b.min()

0.0447112597482312

In [55]:
b.shape

(5, 3, 2)

In [60]:
b.reshape((1,1,2,1,1,15))

array([[[[[[0.8180361 , 0.45600498, 0.04471126, 0.34612086,
            0.30714511, 0.44638296, 0.21723355, 0.14495298,
            0.1534135 , 0.57836215, 0.68645639, 0.08419984,
            0.95556353, 0.72185678, 0.35789369]]],


         [[[0.59625938, 0.6629485 , 0.25928965, 0.946139  ,
            0.16530205, 0.54314783, 0.46087273, 0.79653774,
            0.15828406, 0.09042659, 0.42157672, 0.29883988,
            0.25327702, 0.65605426, 0.26425126]]]]]])

In [62]:
type(a.tolist())

list

In [64]:
a.transpose()

array([[0.01733484, 0.38574169, 0.18910638, 0.13002704, 0.75652062,
        0.47703189, 0.82566561, 0.35370038, 0.16727522, 0.31731437],
       [0.87489855, 0.85367326, 0.21608436, 0.97636184, 0.27855374,
        0.41319131, 0.07674766, 0.47614875, 0.50411282, 0.39769779],
       [0.66409092, 0.55649259, 0.47976771, 0.33887282, 0.068987  ,
        0.94953295, 0.54446454, 0.15385181, 0.64836588, 0.0334028 ],
       [0.08008466, 0.11081625, 0.54687445, 0.22873085, 0.31648942,
        0.28593424, 0.19239926, 0.79406025, 0.1742123 , 0.52873753]])

In [65]:
a.T

array([[0.01733484, 0.38574169, 0.18910638, 0.13002704, 0.75652062,
        0.47703189, 0.82566561, 0.35370038, 0.16727522, 0.31731437],
       [0.87489855, 0.85367326, 0.21608436, 0.97636184, 0.27855374,
        0.41319131, 0.07674766, 0.47614875, 0.50411282, 0.39769779],
       [0.66409092, 0.55649259, 0.47976771, 0.33887282, 0.068987  ,
        0.94953295, 0.54446454, 0.15385181, 0.64836588, 0.0334028 ],
       [0.08008466, 0.11081625, 0.54687445, 0.22873085, 0.31648942,
        0.28593424, 0.19239926, 0.79406025, 0.1742123 , 0.52873753]])

In [67]:
np.dot(a[0], a[0].T)

1.2131782781955387

In [70]:
np.matmul(a, a.T)

array([[1.21317828, 1.13200063, 0.55473566, 1.09983175, 0.32798002,
        1.02324491, 0.45844138, 0.58847683, 0.88847289, 0.41797208],
       [1.13200063, 1.19951894, 0.58500141, 1.09757815, 0.60307835,
        1.09683568, 0.70832252, 0.71652461, 0.87498902, 0.53908648],
       [0.55473566, 0.58500141, 0.6117024 , 0.52323276, 0.4094317 ,
        0.79141934, 0.53915735, 0.67783969, 0.54690098, 0.45112108],
       [1.09983175, 1.09757815, 0.52323276, 1.13734206, 0.46610609,
        0.85262416, 0.41080422, 0.74464635, 0.77350812, 0.56181428],
       [0.32798002, 0.60307835, 0.4094317 , 0.46610609, 0.75484039,
        0.63198104, 0.74446471, 0.66214009, 0.36683483, 0.52047926],
       [1.02324491, 1.09683568, 0.79141934, 0.85262416, 0.63198104,
        1.3816577 , 0.99758085, 0.73860326, 0.95354868, 0.49859557],
       [0.45844138, 0.70832252, 0.53915735, 0.41080422, 0.74446471,
        0.99758085, 1.02107301, 0.565125  , 0.56333342, 0.41243329],
       [0.58847683, 0.71652461, 0.6778396

In [73]:
a.var()**0.5

0.2686702121380383

In [74]:
a.std()

0.2686702121380383

In [79]:
a[:4, :].shape

(4, 4)

In [80]:
np.linalg.det(a[:4, :])

-0.07688120645073505

In [81]:
# https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [84]:
np.inf

inf

# Pandas